### ISSUE TITLE
ChroPath? and Search Terms

### ISSUE THREAD

**Issue by steveflemmy123** [D-a-n-i-e-l/poshmarkFollowbot#1]
do you have to make any modifications for chropath to work on chrome
when it comes to search terms do I just plug them in without erasing anything you've put up

**Comment by D-a-n-i-e-l** [comment]
> do you have to make any modifications for chropath to work on chrome

Not that I'm aware of. I just added the extension and it works.
> when it comes to search terms do I just plug them in without erasing anything you've put up

when you run the script in a terminal, it will prompt you with the question 'What would you like to search for? Please separate multpile keywords with a space: '"  This is where you enter in your keywords separated by a space. you don't have to replace anything in the code. press enter when done and the script plugs in the input

**Comment by steveflemmy123** [comment]
I was writing through the atom IDE, I went back to the default python gives and it worked. thanks
